services:
  bot:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      AUTH_USERS: $AUTH_USERS
      GROUPS: $AUTH_GROUPS
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
